/*
* Copyright (c) 2025 Rahul Anishetty
*
* This program is dual-licensed under either AGPL-3.0 or a commercial license.
* For commercial licensing options, please contact the author.
* For AGPL-3.0 licensing details, see the LICENSE file in the repository root.
*/
package com.upo.orchestrator.engine;

/**
 * Represents a variable created during process execution. Variables capture task inputs, outputs,
 * errors, and state changes as tasks execute within a process.
 */
public interface Variable {

  /** Types of variables in process execution. */
  enum Type {
    /**
     * Processed input values provided to a task. Represents the actual values after variable
     * resolution that were used for task execution.
     */
    INPUT("i"),
    /**
     * Output values produced by a task. Represents the results/data generated by successful task
     * execution.
     */
    OUTPUT("o"),
    /**
     * Error information when task execution fails. Contains error details, stack traces, and any
     * error-specific data.
     */
    ERROR("e"),
    /**
     * State changes during task execution. Represents intermediate state or metadata produced
     * during task processing.
     */
    STATE("s");

    private final String abbr;

    Type(String abbr) {
      this.abbr = abbr;
    }

    public String getAbbr() {
      return abbr;
    }
  }

  /**
   * Returns the ID of the task that created this variable. Used to track which task produced or
   * consumed this variable during process execution.
   *
   * @return task identifier
   */
  String getTaskId();

  /**
   * Returns the type of this variable. Variable types indicate the variable's role in process
   * execution: - INPUT: Processed input values used by task - OUTPUT: Values produced by task
   * execution - ERROR: Error details when task fails - STATE: State changes during task execution
   *
   * @return variable type
   */
  Type getType();

  /**
   * Returns the actual data/value of this variable. The structure and content of payload depends on
   * the variable type and task implementation.
   *
   * @return variable payload
   */
  Object getPayload();
}
